### ISSUE TITLE
Modal 3.7.x break in Next.js

### ISSUE THREAD

**Issue by sunaryohadi** [react-materialize/react-materialize#1085]
### Description

Since Next.js is SSR, it will not recognize the document

Need to modify this line 34 on Modal.js

```var MODAL_CONTAINER = document.body;```

into 

```var MODAL_CONTAINER = (typeof window !== 'undefined')  ? document.body : null;```

I know, the modal might not work in Next.js anyway, but I still can use the rest of components in react-materialize without breaking.

**Comment by louishugens** [comment]
Same happen in Gatsby too:

  32 | function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }
  33 |
> 34 | var MODAL_CONTAINER = document.body;
     | ^
  35 |
  36 | var Modal = function Modal(_ref) {
  37 |   var actions = _ref.actions,


  WebpackError: ReferenceError: document is not defined

**Comment by alextrastero** [comment]
Yup, good catch, will fix

**Comment by drreyes** [comment]
There is a new error with the modal when using NextJS (SSR). When I start the server I get the following error

```console
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/dr/Documents/DAHU/Proyectos/web/node_modules/react-materialize/lib/Modal.js:217:94)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dr/Documents/DAHU/Proyectos/web/node_modules/react-materialize/lib/index.js:353:37)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
### Versions
**react-materialize:** 3.8.3
**materialize-css:** 1.0.0
**next:** 9.3.2
**react:** 16.13.1

I tried using another version of the package but it didn't work either.

**Comment by sunaryohadi** [comment]
FYI, Modal still working fine with react-materialize@3.6.x and NextJS.
After that until the latest one 3.8.5, error "Modal is not defined" or  in some release are "Element is not defined".

**Comment by alextrastero** [comment]
`Element is not defined` should be solved `3.8.4` and `Modal is not defined` is another story completely.

Can you try using the `Dropdown` component in `3.8.5` and see if you get any errors?

**Comment by sunaryohadi** [comment]
Modal just break directly when app is start or loading.

```
document is not defined
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/shadi/project/mza/mzaweb/node_modules/react-materialize/lib/Modal.js:225:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/shadi/project/mza/mzaweb/node_modules/react-materialize/lib/index.js:356:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Dropdown 3.8.5 is working fine in NextJS (testing with commenting out the Modal interop)

**Comment by alextrastero** [comment]
`document is not defined`
For server side rendering you need to supply a `root` prop:
`<Modal root={document.getElementById('something')} ...`

**Comment by sunaryohadi** [comment]
Unfortunately, it breaks the whole App right away.  Just when it started.
Even if my App not using Modal anyway.

**Comment by alextrastero** [comment]
Give this a go, this is very nextjs specific, https://github.com/zeit/next.js/tree/85769c3d3296cdcddc0fb36f05058c8e451ca57f/examples/with-portals

**Comment by sunaryohadi** [comment]
To avoid broken on the first run (while loading on NextJS) ...

I change Modal.js at line 225
```
  root: document.body,
```
into
```
  root: typeof window !== 'undefined' ? document.body : null,
```
and it's working ok.
I think It's should be ok for regular react anyway.

I still can use the Modal, using Non-SSR technique when I use it on NextJS.

**Comment by alextrastero** [comment]
Fixed in `3.8.6`

**Comment by sunaryohadi** [comment]
Error still occurs in 3.8.6. I think  you forgot the quote on last undefined
```
root: (typeof window === "undefined" ? "undefined" : _typeof(window)) !== undefined ? document.body : null,
```
