### ISSUE TITLE
Collapsible accordion={false} does not work

### ISSUE THREAD

**Issue by domantasjurkus** [react-materialize/react-materialize#729]
### Description
The [Basic Collapsible example](https://react-materialize.github.io/#/collapsible) does not allow opening multiple collapsible elements when copy-pasted to my own project. Adding an explicit `accordion={false}` did not solve my issue. In addition, editing the docs directly by adding `accordion={true}` does not produce expected behaviour (allowing single element to be opened at a time).

### Steps to Reproduce
1. Paste the following code into a plan React project:
```
<Collapsible>
  <CollapsibleItem header='First' icon='filter_drama'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Second' icon='place'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Third' icon='whatshot'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
</Collapsible>
```
...or the following code with the explicit accordion prop:
```
<Collapsible accordion={false}>
  <CollapsibleItem header='First' icon='filter_drama'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Second' icon='place'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Third' icon='whatshot'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
</Collapsible>
```
...or edit the Basic Collapsible example to include `<Collapsible accordion={true}>` and see unexpected behaviour.

**Expected behavior:**
Multiple collapsible items should be openable.

**Actual behavior:**
Only a single collapsible is openable.

### Versions
**react-materialize:** 2.6.0 (also tried 2.4.6)
**materialize-css:** None, not using (should I?)
**react:** 16.6.3

**Comment by alextrastero** [comment]
Solved in 3.x

**Comment by JHaydenDev** [comment]
Same situation.  Version 3.9 accordion={false} still doesn't work
